[2025-10-04T14:11:55.605+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-04T14:11:55.617+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retail_mlops_data_pipeline.process_data_and_train_model manual__2025-10-04T14:07:27.305089+00:00 [queued]>
[2025-10-04T14:11:55.623+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retail_mlops_data_pipeline.process_data_and_train_model manual__2025-10-04T14:07:27.305089+00:00 [queued]>
[2025-10-04T14:11:55.623+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-10-04T14:11:55.639+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): process_data_and_train_model> on 2025-10-04 14:07:27.305089+00:00
[2025-10-04T14:11:55.647+0000] {standard_task_runner.py:63} INFO - Started process 5329 to run task
[2025-10-04T14:11:55.649+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'retail_mlops_data_pipeline', 'process_data_and_train_model', 'manual__2025-10-04T14:07:27.305089+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/retail_mlops_data_pipeline.py', '--cfg-path', '/tmp/tmp_q7miuve']
[2025-10-04T14:11:55.650+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask process_data_and_train_model
[2025-10-04T14:11:55.688+0000] {task_command.py:426} INFO - Running <TaskInstance: retail_mlops_data_pipeline.process_data_and_train_model manual__2025-10-04T14:07:27.305089+00:00 [running]> on host ip-172-31-17-35.ec2.internal
[2025-10-04T14:11:55.749+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='retail_mlops_data_pipeline' AIRFLOW_CTX_TASK_ID='process_data_and_train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-10-04T14:07:27.305089+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-04T14:07:27.305089+00:00'
[2025-10-04T14:11:55.750+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-04T14:11:55.761+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-04T14:11:55.762+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/airflow/dags/retail_mlops_data_pipeline.py", line 36, in process_and_train
    raise FileNotFoundError(f"Raw data not found at {FULL_FILE_PATH}. Please place the CSV here.")
FileNotFoundError: Raw data not found at /opt/airflow/dags/data/customer_shopping_data.csv. Please place the CSV here.
[2025-10-04T14:11:55.766+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=retail_mlops_data_pipeline, task_id=process_data_and_train_model, execution_date=20251004T140727, start_date=20251004T141155, end_date=20251004T141155
[2025-10-04T14:11:55.780+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task process_data_and_train_model (Raw data not found at /opt/airflow/dags/data/customer_shopping_data.csv. Please place the CSV here.; 5329)
[2025-10-04T14:11:55.822+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-04T14:11:55.838+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-04T14:11:55.840+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
